name: "Create Release Draft"
description: >
  Generates a draft release, calculating the next semantic version
  from PR labels, and creating release notes from the target branch or commit
on: 
  workflow_call:
    inputs:
      target: 
        description: "Release target to be used"
        type: string
        required: true
      semver-bump-labels:
        description: "Comma-separated list of PR labels used to bump version"
        type: string
        required: true
jobs:
  draft:
    name: "Create Release Draft"
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout target"
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.target }}
          
      - name: "Get base"
        id: base
        run: |
          version=$(npm pkg get version | tr -d \")
          echo "version=${version}" >> "$GITHUB_OUTPUT" 
          echo "tag=v${version}" >> "$GITHUB_OUTPUT" 

      - name: "Bump version"
        id: bumper
        uses: t15i/semver-bump-action@v1.0.0
        with:
          labels: ${{ inputs.semver-bump-labels }}
          basehead: ${{ steps.base.outputs.tag }}...${{ inputs.target }}
          version: ${{ steps.base.outputs.version }}

      - name: "Compute head"
        id: head
        run: |
          echo "version=${{steps.bumper.outputs.bumped_version}}" >> "$GITHUB_OUTPUT" 
          echo "tag=v${{steps.bumper.outputs.bumped_version}}" >> "$GITHUB_OUTPUT" 

      - name: "Pack"
        id: pack
        uses: t15i/workflows/.github/actions/nodejs/pack@main
        with:
          ref: ${{ inputs.target }}
          version: ${{ steps.head.outputs.version }}

      - name: "Create release draft"
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ steps.head.outputs.tag }} \
            --draft \
            --generate-notes \
            --notes-start-tag ${{ steps.base.outputs.tag }} \
            --target ${{ inputs.target }}

      - name: "Upload artifact to release draft"
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ steps.head.outputs.tag }} \
            ${{ steps.pack.outputs.package-path }}
