name: "Publish Release"
description: >
  Packages a tagged release, publishes it to npm, 
  and commits the released version back to the specified branch
on:
  workflow_call:
    inputs:
      tag:
        description: "Git tag to package and publish"
        type: string
        required: true
      branch:
        description: "Branch to which version will be pushed after publication"
        type: string
        required: true
      git-user-name:
        description: "Git user name used for the version bump commit"
        type: string
        default: release-ci[bot]
      git-user-email:
        description: "Git user email used for the version bump commit"
        type: string
    secrets:
      RELEASE_BOT_ID:
        required: true
      RELEASE_BOT_PRIVATE_KEY:
        required: true
      NPM_TOKEN:
        required: true
jobs:
  publish:
    name: "Publish Package"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Download artifacts from release draft"
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release download ${{ inputs.tag }} 

      - name: "Compute package path"
        id: package-path
        run: | 
          package_path=$(ls -1 | grep -E '.+-[0-9]+\.[0-9]*\.[0-9]+.*\.tgz' | head -n1)
          echo "value=$package_path" >> "$GITHUB_OUTPUT" 

      - name: "Publish package"
        uses: t15i/workflows/.github/actions/nodejs/publish@main
        with:
          registry-url: https://registry.npmjs.org
          registry-token: ${{ secrets.NPM_TOKEN }}
          package-path: ${{ steps.package-path.outputs.value }}

  commit:
    name: "Commit Bumped Version"
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - id: token-generator
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.RELEASE_BOT_ID }}
          private-key: ${{ secrets.RELEASE_BOT_PRIVATE_KEY }}

      - uses: t15i/workflows/.github/actions/nodejs/push-version@main
        with:
          version: ${{ inputs.tag }}
          branch: ${{ inputs.branch }}
          git-user-name: ${{ inputs.git-user-name }}
          git-user-email: >-
            ${{ inputs.git-user-email || 
                format('{0}+{1}@users.noreply.github.com', 
                       secrets.RELEASE_BOT_ID, inputs.git-user-name) }}
          token: ${{ steps.token-generator.outputs.token }}
